name: CV-OcrService
channels: !!python/tuple
- defaults
dependencies:
- menpo::opencv3=3.1.0=py35_0
- bioconda::tesseract=3.04.01=0
- python=3.5.2=0
- pip:
  - Flask==0.11.1
  - nameko==2.3.1
  - numpy==1.11.2
  - Pillow==3.4.1
  - pymongo==3.3.1
  - pypng==0.0.18
  - pytesseract==0.1.6
  - pytest==3.0.3
  - kombu==3.0.35
